import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'com.example.recheckstudiosetting'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.recheckstudiosetting"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Gradle Task, Build Speed
//        buildConfigField 'String', 'CUSTOM_KEY', '\"' + new Date() + '\"'

        // Live Template
        // 12_live_templates.kt
//        buildConfigField 'int', 'sample_int', 1.toString()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions.add("donate")
    productFlavors {
        free {
            dimension = 'donate'
        }
        premium {
            dimension = 'donate'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        buildConfig true
        compose true
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_11
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.google.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.espresso.core

    // compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.bundles.compose.android.test
    debugImplementation libs.bundles.compose.debug
}
